; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
upload_port = COM3
board_build.filesystem = littlefs

lib_deps =
    adafruit/RTClib @ ^2.1.1    
    bblanchon/ArduinoJson @ ^6.21.2
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    bodmer/TFT_eSPI@^2.5.43

build_flags =
    ; -------------------------------------------------------------------------
    ; TFT_eSPI Настройки - НЕ редактируйте User_Setup.h!
    ; -------------------------------------------------------------------------

    ; Указываем, что мы задаем настройки здесь, и отключаем загрузку User_Setup.h
    -D USER_SETUP_LOADED=1

    ; --- Выбор драйвера ---
    -D ILI9341_DRIVER

    ; --- Пины подключения (Пример для ESP32 VSPI) ---
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15  ; Chip select control pin
    -D TFT_DC=16  ; Data Command control pin
    -D TFT_RST=3  ; Reset pin (or -1 if not used)
    ; -D TFT_BL=22  ; LED back-light (если используется и управляется)

    ; --- Пины Touch Screen (если есть и используются) ---
    -D TOUCH_CS=0 ; Touch Screen Chip Select

    ; --- Настройки SPI ---
    -D SPI_FREQUENCY=40000000 ; 40 MHz
    ; -D SPI_READ_FREQUENCY=20000000 ; Опционально
    ; -D SPI_TOUCH_FREQUENCY=2500000 ; Опционально

    ; --- Включение шрифтов ---
    ;-D LOAD_GLCD  ; Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
    -D LOAD_FONT2 ; Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
    -D LOAD_FONT4 ; Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
    ;-D LOAD_FONT6 ; Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
    ;-D LOAD_FONT7 ; Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:-.
    ;-D LOAD_FONT8 ; Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
    ; -D LOAD_FONT8N ; Font 8. Alternative font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
    -D LOAD_GFXFF ; FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

    ; --- Включение поддержки Smooth Fonts (сглаженных шрифтов) ---
    -D SMOOTH_FONT

    ; -------------------------------------------------------------------------
    ; Конец настроек TFT_eSPI
    ; -------------------------------------------------------------------------