#include "main.h"

#if defined(LANG_RU)
const char* const strings[] = {
    "ТРЕВОГА: Ошибка датчика нагрева!",
    "ТРЕВОГА: Ошибка датчика влажности!",
    "Целевые значения t2/RH достигнуты.",
    "ТРЕВОГА: t2/RH вне диапазона!",
    "Целевое значение t1 достигнуто.",
    "ТРЕВОГА: t1 вне диапазона!",
    "КВАДУС версия: 0.0",
    "Датчики: DHT22 обнаружен",
    "Датчики: DS18B20 обнаружено",
    "Датчики: НЕ ОБНАРУЖЕНЫ",
    "Ежедневная синхронизация RTC успешна.",
    "ОШИБКА: Файловой системы",
    "ОШИБКА: Сбой сериализации JSON",
    "Конфигурация сохранена в ФС.",
    "Ручное управление активировано.",
    "Ручное: Свет ",
    "Ручное: Нагрев ",
    "Ручное: Увлажн. ",
    "Ручное: Реле1 ",
    "Ручное: Реле2 ",
    "Ручное: Реле3 ",
    "Автоматическое управление восстановлено.",
    "Лог очищен (лимит размера).",
    "ОШИБКА: Датчик DHT22 не отвечает!",
    "Датчик DHT22: связь восстановлена.",
    "ТРЕВОГА: Датчик T1 завис!",
    "ТРЕВОГА: Датчик T2 завис!",
    "Датчик T1: показания изменились.",
    "Датчик T2: показания изменились.",
    "Данные за текущие сутки очищены."
};
#elif defined(LANG_UA)
const char* const strings[] = {
    "ТРИВОГА: Помилка датчика нагріву!",
    "ТРИВОГА: Помилка датчика вологості!",
    "Цільові значення t2/RH досягнуті.",
    "ТРИВОГА: t2/RH поза діапазоном!",
    "Цільове значення t1 досягнуто.",
    "ТРИВОГА: t1 поза діапазоном!",
    "КВАДУС версія: 0.0",
    "Датчики: DHT22 виявлено",
    "Датчики: DS18B20 виявлено",
    "Датчики: НЕ ВИЯВЛЕНО",
    "Щоденна синхронізація RTC успішна.",
    "ПОМИЛКА: Файлової системи",
    "ПОМИЛКА: Збій серіалізації JSON",
    "Конфігурація збережена у ФС.",
    "Ручне управління активовано.",
    "Ручне: Світло ",
    "Ручне: Нагрів ",
    "Ручне: Зволож. ",
    "Ручне: Реле1 ",
    "Ручне: Реле1 ",
    "Ручне: Реле1 ",
    "Автоматичне управління відновлено.",
    "Лог очищено (ліміт розміру).",
    "ПОМИЛКА: Датчик DHT22 не відповідає!",
    "Датчик DHT22: зв'язок відновлено.",
    "ТРИВОГА: Датчик T1 завис!",
    "ТРИВОГА: Датчик T2 завис!",
    "Датчик T1: показники змінилися.",
    "Датчик T2: показники змінилися.",
    "Дані за поточну добу очищено."
};
#else // Default to English (LANG_EN)
const char* const strings[] = {
    "ALARM: Heater sensor error!",
    "ALARM: Humidity sensor error!",
    "Climate t2/RH target reached.",
    "ALARM: t2/RH out of range!",
    "Climate t1 target reached.",
    "ALARM: t1 temperature out of range!",
    "QUADUS version: 0.0",
    "Sensors: DHT22 detected",
    "Sensors: DS18B20 detected",
    "Sensors: NONE found",
    "Daily RTC sync successful.",
    "ERROR: File system",
    "ERROR: JSON serialization failed",
    "Configuration saved to FS.",
    "Manual override activated.",
    "Manual: Light ",
    "Manual: Heater ",
    "Manual: Humidi ",
    "Manual: Relay1 ",
    "Manual: Relay2 ",
    "Manual: Relay3 ",
    "Automatic control restored.",
    "Log rotated (size limit).",
    "ERROR: DHT22 sensor timeout!",
    "DHT22 sensor: connection restored.",
    "ALARM: Sensor T1 frozen!",
    "ALARM: Sensor T2 frozen!",
    "Sensor T1: readings updated.",
    "Sensor T2: readings updated.",
    "Daily graph data cleared."
};
#endif

const char* getMsg(LogMsgId id) {
    return strings[id];
}
